# Generated by Django 5.1.2 on 2026-10-04 12:26

from django.db import migrations, models


def links_become_reusable(apps, schema_editor):
    """Los enlaces compartidos (sin email) pendientes pasan a servir para varias personas."""
    apps.get_model("core", "Invitation").objects.filter(email="", used_at__isnull=True).update(reusable=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_photo_reviewed_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="reusable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invitation",
            name="use_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(links_become_reusable, migrations.RunPython.noop),
    ]
