# Generated by Django 5.1.2 on 2026-10-04 16:59

from django.db import migrations, models
from django.utils import timezone


def hide_for_existing_clubs(apps, schema_editor):
    """Los clubes que ya existían no ven la lista de primeros pasos: es para los nuevos."""
    apps.get_model("core", "Club").objects.update(onboarding_dismissed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_invitation_reusable"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="onboarding_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(hide_for_existing_clubs, migrations.RunPython.noop),
    ]
