"""
Django settings for zyra project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import datetime
from pathlib import Path
import os
import dj_database_url
from cryptography.fernet import Fernet
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Configuración por entorno
#
# Todo lo que cambia entre tu ordenador y producción sale de variables de entorno
# (o del fichero .env junto a manage.py; hay un ejemplo en .env.example). Por
# defecto la aplicación arranca en modo PRODUCCIÓN (DEBUG desactivado) y se niega a
# arrancar si faltan las claves: así un olvido en el servidor no deja la web abierta.
# En tu ordenador pon DJANGO_DEBUG=True en el .env.
# ---------------------------------------------------------------------------

DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

# Valores que nunca valen en producción (incluido el que se usaba antes por defecto).
INSECURE_SECRET_KEYS = {'', 'clave_por_defecto_no_segura', 'django-insecure-solo-para-desarrollo'}

SECRET_KEY = config('DJANGO_SECRET_KEY', default='')
if not DEBUG and (SECRET_KEY in INSECURE_SECRET_KEYS or len(SECRET_KEY) < 50):
    raise ImproperlyConfigured(
        "Falta DJANGO_SECRET_KEY o es demasiado corta (mínimo 50 caracteres). Genera una con: "
        "python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\" "
        "(en tu ordenador también puedes poner DJANGO_DEBUG=True en el .env)."
    )
SECRET_KEY = SECRET_KEY or 'django-insecure-solo-para-desarrollo'

# Clave Fernet para cifrar datos sensibles guardados en la base de datos (credenciales
# de SNP de cada club). Ver core/crypto.py. En producción es obligatoria: sin ella la
# clave se derivaría de DJANGO_SECRET_KEY.
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default='')
if FIELD_ENCRYPTION_KEY:
    try:
        Fernet(FIELD_ENCRYPTION_KEY)
    except (ValueError, TypeError):
        raise ImproperlyConfigured(
            "FIELD_ENCRYPTION_KEY no es una clave Fernet válida. Genera una con: "
            "python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
        )
elif not DEBUG:
    raise ImproperlyConfigured(
        "Falta FIELD_ENCRYPTION_KEY (cifra las cuentas SNP de los clubes). Genera una con: "
        "python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    )

# Dominios desde los que se sirve la web, separados por comas: "zyra.es,www.zyra.es".
ALLOWED_HOSTS = config('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())
# Orígenes HTTPS de confianza para los formularios: "https://zyra.es,https://www.zyra.es".
CSRF_TRUSTED_ORIGINS = config('DJANGO_CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# URL pública y única de la web, sin barra final: "https://zyra.es". Se usa en las URLs
# canónicas, la vista previa al compartir (Open Graph) y el sitemap. Si está definida, las
# peticiones a cualquier otro dominio de ALLOWED_HOSTS (p. ej. www.zyra.es) se redirigen
# aquí con un 301 (core.middleware.CanonicalHostMiddleware). Vacía en local.
SITE_URL = config('SITE_URL', default='').rstrip('/')

# Datos del responsable de la web que exigen el aviso legal y la política de privacidad
# (LSSI-CE art. 10 y RGPD art. 13). Mientras falten, las páginas legales lo avisan.
LEGAL_OWNER_NAME = config('LEGAL_OWNER_NAME', default='')
LEGAL_OWNER_ID = config('LEGAL_OWNER_ID', default='')  # NIF/DNI
LEGAL_OWNER_ADDRESS = config('LEGAL_OWNER_ADDRESS', default='')

# Ruta del Django admin (herramienta de emergencia, solo superusuarios). Se puede
# cambiar por una menos obvia con la variable de entorno ADMIN_URL.
ADMIN_URL = config('ADMIN_URL', default='admin/')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'
# Formularios rechazados por CSRF: misma página «Sin permiso» que el resto de la web.
CSRF_FAILURE_VIEW = 'core.views.csrf_failure'

# HTTPS en producción: redirección a https, cookies solo por https y HSTS.
if not DEBUG:
    SECURE_SSL_REDIRECT = config('DJANGO_SECURE_SSL_REDIRECT', default=True, cast=bool)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Empieza con 1 hora; cuando todo funcione por https súbelo a un año (31536000).
    SECURE_HSTS_SECONDS = config('DJANGO_SECURE_HSTS_SECONDS', default=3600, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
    # HSTS para subdominios y la lista "preload" de los navegadores son decisiones difíciles
    # de deshacer: se activan a mano cuando haya dominio definitivo, no por defecto.
    SILENCED_SYSTEM_CHECKS = ['security.W005', 'security.W021']
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    # Si el hosting pone delante un proxy que termina el https (lo habitual), activa
    # esto para que Django sepa que la petición original era https y no entre en bucle.
    if config('DJANGO_BEHIND_PROXY', default=False, cast=bool):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'players',
    'core',
    'match',
    'call',
    "django_flatpickr",
    'data_analyse',
    'team',
    'callLog',
    'penalty',
    'backoffice',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Un solo dominio: redirige con 301 a SITE_URL (www → sin www, dominio antiguo...).
    'core.middleware.CanonicalHostMiddleware',
    # Mide todas las peticiones y la última actividad de cada usuario (back-office).
    'backoffice.middleware.ActivityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Idioma de la interfaz: el elegido en el selector (cookie) o español (core/middleware.py).
    'core.middleware.LanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CurrentClubMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'zyra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.club',
                'core.context_processors.navigation',
                'core.context_processors.google_login',
                'core.context_processors.site',
            ],
        },
    },
]

WSGI_APPLICATION = 'zyra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Con DATABASE_URL se usa esa base de datos (PostgreSQL en producción), por ejemplo
#   DATABASE_URL=postgres://usuario:contraseña@localhost:5432/zyra
# Sin ella, el fichero SQLite db.sqlite3 junto a manage.py (cómodo para desarrollar).
DATABASE_URL = config('DATABASE_URL', default='')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            # Reutiliza la conexión entre peticiones (segundos) y comprueba que sigue viva.
            conn_max_age=config('DATABASE_CONN_MAX_AGE', default=60, cast=int),
            conn_health_checks=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# La web está en español y se puede ver en inglés con el selector de idioma de la
# cabecera. Los textos se escriben en español en el código ({% translate %}, gettext) y
# las traducciones al inglés están en locale/en/LC_MESSAGES/django.po. Tras cambiar
# textos: python manage.py makemessages -l en -d django && makemessages -l en -d djangojs
# (ignora venv y staticfiles), traduce los nuevos en el .po y python manage.py compilemessages.
LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Ficheros subidos por los usuarios (escudos y fotos de jugador): nunca en static/, que es
# solo para los ficheros del código. Se guardan en MEDIA_ROOT (carpeta media/, fuera de git)
# y se ven en MEDIA_URL. En local los sirve Django (DJANGO_DEBUG=True); en el servidor, el
# servidor web (Caddy, Nginx) desde esa carpeta, que debe estar en un disco persistente.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(config('DJANGO_MEDIA_ROOT', default=str(BASE_DIR / 'media')))

# Dónde se guardan: por defecto en el disco (MEDIA_ROOT). Para usar un bucket compatible con
# S3 (Hetzner Object Storage, Cloudflare R2, AWS S3...) basta con instalar django-storages[s3]
# y poner DJANGO_MEDIA_STORAGE=storages.backends.s3.S3Storage y las variables AWS_* del .env.
MEDIA_STORAGE = config('DJANGO_MEDIA_STORAGE', default='django.core.files.storage.FileSystemStorage')
STORAGES = {
    'default': {'BACKEND': MEDIA_STORAGE},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}
if MEDIA_STORAGE.startswith('storages.backends.s3'):
    STORAGES['default']['OPTIONS'] = {
        'bucket_name': config('AWS_STORAGE_BUCKET_NAME'),
        'endpoint_url': config('AWS_S3_ENDPOINT_URL', default=None),
        'region_name': config('AWS_S3_REGION_NAME', default=None),
        'access_key': config('AWS_ACCESS_KEY_ID'),
        'secret_key': config('AWS_SECRET_ACCESS_KEY'),
        # Dominio público del bucket (o de su CDN); sin él las URLs se firman y caducan.
        'custom_domain': config('AWS_S3_CUSTOM_DOMAIN', default=None),
        'querystring_auth': not config('AWS_S3_CUSTOM_DOMAIN', default=''),
        'file_overwrite': False,
    }

# Procesado de las fotos al subirlas (core/images.py): tamaño máximo del fichero subido,
# lado máximo en píxeles tras reducirla y calidad del WebP (0-100).
PHOTO_MAX_UPLOAD_MB = config('PHOTO_MAX_UPLOAD_MB', default=10, cast=int)
PHOTO_MAX_SIZE = config('PHOTO_MAX_SIZE', default=512, cast=int)
PHOTO_WEBP_QUALITY = config('PHOTO_WEBP_QUALITY', default=82, cast=int)

# Validación automática (opcional) de las fotos con AWS Rekognition (core/moderation.py), SOLO dentro
# del plan gratuito: como mucho REKOGNITION_MONTHLY_LIMIT fotos al mes (1.000 gratis en
# DetectModerationLabels) y hasta REKOGNITION_FREE_UNTIL (AAAA-MM-DD, fin del periodo
# gratuito de la cuenta). Sin claves, después de esa fecha o pasado el límite, las fotos se
# aceptan "sin validar" y el personal las revisa en el back-office (Fotos).
# Desactivada por defecto: la revisión la hace el personal en el back-office (Fotos).
REKOGNITION_ENABLED = config('REKOGNITION_ENABLED', default=False, cast=bool)
REKOGNITION_ACCESS_KEY_ID = config('REKOGNITION_ACCESS_KEY_ID', default='')
REKOGNITION_SECRET_ACCESS_KEY = config('REKOGNITION_SECRET_ACCESS_KEY', default='')
REKOGNITION_REGION = config('REKOGNITION_REGION', default='eu-west-1')
REKOGNITION_FREE_UNTIL = config(
    'REKOGNITION_FREE_UNTIL', default='',
    cast=lambda v: datetime.date.fromisoformat(v) if v else None,
)
REKOGNITION_MONTHLY_LIMIT = config('REKOGNITION_MONTHLY_LIMIT', default=1000, cast=int)
REKOGNITION_MIN_CONFIDENCE = config('REKOGNITION_MIN_CONFIDENCE', default=80, cast=float)
# Categorías de Rekognition que hacen rechazar la foto (nombre o categoría superior).
REKOGNITION_BLOCKED_LABELS = config(
    'REKOGNITION_BLOCKED_LABELS', cast=Csv(),
    default='Explicit,Explicit Nudity,Non-Explicit Nudity,'
            'Violence,Graphic Violence Or Gore,Visually Disturbing,Hate Symbols',
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email (informes de convocatoria). Se envían desde join.zyra@gmail.com por
# Gmail. La contraseña de aplicación NUNCA va en el código: se define en la
# variable de entorno EMAIL_HOST_PASSWORD (o en .env). Mientras no exista, los
# correos se muestran en la consola en lugar de enviarse.
ZYRA_SENDER = 'join.zyra@gmail.com'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=ZYRA_SENDER)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_TIMEOUT = 20
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=f'Zyra <{ZYRA_SENDER}>')
# Correo de contacto que se muestra en el pie y en las páginas legales.
CONTACT_EMAIL = config('CONTACT_EMAIL', default=ZYRA_SENDER)
# Los informes de convocatoria se guardan en una cola (match.ReportDelivery): se intenta
# enviarlos al cerrar la convocatoria y, si falla, el proceso send_call_reports los
# reintenta con esperas crecientes. Como mucho EMAIL_MAX_PER_RUN correos por pasada,
# para no pasar del límite del proveedor (Gmail: unos 500 al día).
EMAIL_MAX_PER_RUN = config('EMAIL_MAX_PER_RUN', default=100, cast=int)

# Actualización de los puntos SNP (update_snp_scores): clubes por lote, pausa aleatoria
# entre club y club, pausa entre lotes (en segundos) y cuántos fallos de red seguidos
# hacen parar el proceso.
SNP_BATCH_SIZE = config('SNP_BATCH_SIZE', default=50, cast=int)
SNP_PAUSE_MIN_SECONDS = config('SNP_PAUSE_MIN_SECONDS', default=5, cast=float)
SNP_PAUSE_MAX_SECONDS = config('SNP_PAUSE_MAX_SECONDS', default=15, cast=float)
SNP_BATCH_PAUSE_SECONDS = config('SNP_BATCH_PAUSE_SECONDS', default=60, cast=float)
SNP_MAX_CONSECUTIVE_FAILURES = config('SNP_MAX_CONSECUTIVE_FAILURES', default=5, cast=int)

# «Completar equipo» desde la web: una vez al mes y pocas búsquedas al día (players/snp_import.py).
# Los clubes de esta lista (por nombre del club o de su equipo, sin distinguir mayúsculas ni
# tildes) no tienen esos límites: es el equipo de pruebas. Se cambia con la variable de
# entorno SNP_IMPORT_UNLIMITED_CLUBS, nombres separados por comas.
SNP_IMPORT_UNLIMITED_CLUBS = config('SNP_IMPORT_UNLIMITED_CLUBS', default='Los Gladiadores', cast=Csv())


# Inicio de sesión: con usuario o email y contraseña (formulario propio) o con
# Google (django-allauth). El ID y el secreto de cliente de Google NUNCA van en el
# código: se definen en las variables de entorno GOOGLE_CLIENT_ID y
# GOOGLE_CLIENT_SECRET (o en .env). Mientras no existan, el botón de Google no aparece.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')
GOOGLE_LOGIN_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)

ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_ADAPTER = 'core.adapters.AccountAdapter'
# Contraseña nueva (olvidada, cambio o primera de una cuenta de Google) con la lista de
# requisitos del registro.
ACCOUNT_FORMS = {
    'reset_password_from_key': 'core.forms.ZyraResetPasswordKeyForm',
    'change_password': 'core.forms.ZyraChangePasswordForm',
    'set_password': 'core.forms.ZyraSetPasswordForm',
}
# Los correos de allauth no llevan «[example.com]» delante del asunto, como el resto de Zyra.
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''
SOCIALACCOUNT_ADAPTER = 'core.adapters.SocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
# Google verifica el email: si ya hay una cuenta con ese email (p. ej. creada por
# un capitán), el jugador entra en ella en lugar de crear otra.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'prompt': 'select_account'},
        **({'APPS': [{'client_id': GOOGLE_CLIENT_ID, 'secret': GOOGLE_CLIENT_SECRET, 'key': ''}]}
           if GOOGLE_LOGIN_ENABLED else {}),
    },
}


# ---------------------------------------------------------------------------
# Logs
#
# Todo va a la salida estándar (la recoge gunicorn, systemd o el hosting). Incluye los
# errores 500 con su traza: sin esto, con DEBUG desactivado Django no los escribe en
# ningún sitio. El nivel se cambia con DJANGO_LOG_LEVEL (DEBUG, INFO, WARNING...).
# ---------------------------------------------------------------------------
LOG_LEVEL = config('DJANGO_LOG_LEVEL', default='INFO').upper()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'root': {'handlers': ['console'], 'level': LOG_LEVEL},
    'loggers': {
        # Errores 500 y 4xx de las peticiones (con traza).
        'django.request': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        'django.security': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
        # El resto de Django solo a partir de WARNING (si no, cada consulta SQL en DEBUG).
        'django': {'handlers': ['console'], 'level': 'WARNING', 'propagate': False},
    },
}

# Sentry (opcional): agrupa los errores y avisa por email. Basta con definir SENTRY_DSN
# (lo da Sentry al crear el proyecto). Sin ella no se envía nada a ningún sitio.
SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=config('SENTRY_ENVIRONMENT', default='development' if DEBUG else 'production'),
        traces_sample_rate=config('SENTRY_TRACES_SAMPLE_RATE', default=0.0, cast=float),
        # No enviar a Sentry datos personales (emails, IPs, cookies).
        send_default_pii=False,
    )
