# Generated by Django 5.1.2 on 2026-10-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0005_draw_result_value"),
        ("team", "0005_photo_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="rival_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Rival"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_matches",
                to="team.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="visiting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visiting_matches",
                to="team.team",
            ),
        ),
    ]
