# Generated by Django 5.1.2 on 2026-10-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0006_player_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="snpteamimport",
            name="error_kind",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
